2017-10-16 09:29:52 Error: Fatal Error (4): syntax error, unexpected 'funcion' (T_STRING), expecting variable (T_VARIABLE) in [/var/www/test3/public_html/app/Controller/TrialsController.php, line 3]
2017-10-16 09:29:52 Error: [FatalErrorException] syntax error, unexpected 'funcion' (T_STRING), expecting variable (T_VARIABLE)
Request URL: /trials
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 3, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 3, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 09:30:14 Error: Fatal Error (1): Class 'AppCOntroller' not found in [/var/www/test3/public_html/app/Controller/TrialsController.php, line 2]
2017-10-16 09:30:14 Error: [FatalErrorException] Class 'AppCOntroller' not found
Request URL: /trials
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Class 'AppCOntr...', '/var/www/test3/...', 2)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'AppCOntr...', '/var/www/test3/...', 2, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Class 'AppCOntr...', '/var/www/test3/...', 2, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 09:40:54 Error: [MissingControllerException] Controller class TrialController could not be found.
Exception Attributes: array (
  'class' => 'TrialController',
  'plugin' => NULL,
)
Request URL: /trial
Stack Trace:
#0 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-10-16 10:46:52 Error: Fatal Error (4): syntax error, unexpected '$this' (T_VARIABLE) in [/var/www/test3/public_html/app/Controller/PostsController.php, line 5]
2017-10-16 10:46:52 Error: [FatalErrorException] syntax error, unexpected '$this' (T_VARIABLE)
Request URL: /posts
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 5)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 5, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 5, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 10:47:16 Error: Fatal Error (1): Class 'AppModel' not found in [/var/www/test3/public_html/app/Controller/PostsController.php, line 2]
2017-10-16 10:47:16 Error: [FatalErrorException] Class 'AppModel' not found
Request URL: /posts
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Class 'AppModel...', '/var/www/test3/...', 2)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'AppModel...', '/var/www/test3/...', 2, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Class 'AppModel...', '/var/www/test3/...', 2, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 11:09:29 Error: [NotFoundException] Invalid Post
Request URL: /posts/view/
Stack Trace:
#0 [internal function]: PostsController->view()
#1 /var/www/test3/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2017-10-16 11:09:48 Error: [NotFoundException] Invalid Post
Request URL: /posts/view/12
Stack Trace:
#0 [internal function]: PostsController->view('12')
#1 /var/www/test3/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(PostsController), Array)
#2 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#4 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2017-10-16 12:55:38 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:55:38 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:55:59 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:55:59 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:56:00 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:56:00 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:56:00 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:56:00 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:58:39 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:58:39 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:58:40 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:58:40 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:58:40 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:58:40 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:58:41 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:58:41 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 12:58:41 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 12:58:41 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 13:00:34 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 13:00:34 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 13:00:35 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 13:00:35 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 13:00:35 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 13:00:35 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 13:00:35 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 13:00:35 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 13:00:36 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 13:00:36 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 13:01:27 Error: [ReflectionException] Class UsersController does not have a constructor, so you cannot pass any constructor arguments
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(243): ReflectionClass->newInstance(Object(CakeRequest), Object(CakeResponse))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(158): Dispatcher->_getController(Object(CakeRequest), Object(CakeResponse))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 13:01:59 Error: Fatal Error (4): syntax error, unexpected 'public' (T_PUBLIC) in [/var/www/test3/public_html/app/Controller/UsersController.php, line 4]
2017-10-16 13:01:59 Error: [FatalErrorException] syntax error, unexpected 'public' (T_PUBLIC)
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(4, 'syntax error, u...', '/var/www/test3/...', 4)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', '/var/www/test3/...', 4, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 14:22:39 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:22:53 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /user/edit
Stack Trace:
#0 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2017-10-16 14:23:05 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:23:10 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:23:20 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:24:27 Error: Fatal Error (1): Call to a member function save() on null in [/var/www/test3/public_html/app/Controller/UsersController.php, line 22]
2017-10-16 14:24:27 Error: [FatalErrorException] Call to a member function save() on null
Request URL: /users/add
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/test3/...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/test3/...', 22, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/test3/...', 22, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 14:30:20 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:30:37 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:32:21 Error: Fatal Error (1): Call to a member function allow() on null in [/var/www/test3/public_html/app/Controller/UsersController.php, line 9]
2017-10-16 14:32:21 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /users/delete/1
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/test3/...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 14:33:55 Error: Fatal Error (1): Call to a member function allow() on null in [/var/www/test3/public_html/app/Controller/UsersController.php, line 9]
2017-10-16 14:33:55 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/test3/...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 14:33:57 Error: Fatal Error (1): Call to a member function allow() on null in [/var/www/test3/public_html/app/Controller/UsersController.php, line 9]
2017-10-16 14:33:57 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/test3/...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 14:34:08 Error: Fatal Error (1): Call to a member function allow() on null in [/var/www/test3/public_html/app/Controller/UsersController.php, line 9]
2017-10-16 14:34:08 Error: [FatalErrorException] Call to a member function allow() on null
Request URL: /users
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Call to a membe...', '/var/www/test3/...', 9)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', '/var/www/test3/...', 9, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 14:38:05 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:40:10 Error: [MissingActionException] Action UsersController::login() could not be found.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
)
Request URL: /users/login
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#1 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#2 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2017-10-16 14:47:58 Error: Fatal Error (1): Class 'BlowfishPasswordHasher' not found in [/var/www/test3/public_html/app/Model/User.php, line 30]
2017-10-16 14:47:58 Error: [FatalErrorException] Class 'BlowfishPasswordHasher' not found
Request URL: /users/add
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Error/ErrorHandler.php(212): ErrorHandler::handleFatalError(1, 'Class 'Blowfish...', '/var/www/test3/...', 30)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Blowfish...', '/var/www/test3/...', 30, Array)
#2 /var/www/test3/public_html/lib/Cake/Core/App.php(970): call_user_func('ErrorHandler::h...', 1, 'Class 'Blowfish...', '/var/www/test3/...', 30, Array)
#3 /var/www/test3/public_html/lib/Cake/Core/App.php(943): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2017-10-16 15:34:03 Error: [PDOException] SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'username' at row 1
Request URL: /users/add
Stack Trace:
#0 /var/www/test3/public_html/lib/Cake/Model/Datasource/DboSource.php(470): PDOStatement->execute(Array)
#1 /var/www/test3/public_html/lib/Cake/Model/Datasource/DboSource.php(436): DboSource->_execute('INSERT INTO `ca...', Array)
#2 /var/www/test3/public_html/lib/Cake/Model/Datasource/DboSource.php(1090): DboSource->execute('INSERT INTO `ca...')
#3 /var/www/test3/public_html/lib/Cake/Model/Model.php(1940): DboSource->create(Object(User), Array, Array)
#4 /var/www/test3/public_html/lib/Cake/Model/Model.php(1758): Model->_doSave(Array, Array)
#5 /var/www/test3/public_html/app/Controller/UsersController.php(22): Model->save(Array)
#6 [internal function]: UsersController->add()
#7 /var/www/test3/public_html/lib/Cake/Controller/Controller.php(491): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#8 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(193): Controller->invokeAction(Object(CakeRequest))
#9 /var/www/test3/public_html/lib/Cake/Routing/Dispatcher.php(167): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest))
#10 /var/www/test3/public_html/app/webroot/index.php(111): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#11 {main}
